# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
