# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_uni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singsong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=60)),
                ('youtubeurl', models.CharField(max_length=20)),
            ],
        ),
    ]
